project:
  type: website
  output-dir: docs

website:
  title: "CGTInformaticsQuarto"
  search: true
  logo: cgt_informatics_bg_removed.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog_posts.qmd
        text: Blog Posts

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



