project:
  type: website
  output-dir: docs

website:
  title: "CGTInformaticsQuarto"
  search: true
  logo: cgt_informatics_bd_removed.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog_posts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



