project:
  type: website
  output-dir: docs

website:
  title: "Cell and Gene Therapy Informatics"
  search: true
  description: CGT Informatics Quarto Site
  navbar:
    logo: img/cgt_informatics_bg_removed.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts
    right:
      - icon: github
        href: https://github.com/CHOP-CGTDataOps
        aria-label: GitHub
  page-footer:
    center:
      - text: "Made with ❤️ in Philadelphia"

format:
  html:
    theme: simplex
    title-block-banner: false
    highlight-style: github
    toc: true



